Repository gdscjgec/Pictionary, pull requests merged in 2021-10, with the labels that each got.

#9 Updated About page and styled Navbar.
  css/about.css
  css/navbar.css
  index.html
  pages/about.html
  pages/images/pic.png
  pages/images/problem.png
Labels: hacktoberfest-accepted

#11 Added footer
  css/footer.css
  index.html
Labels: hacktoberfest-accepted

#14 Improved-Gallery
  css/gallery.css
  pages/gallery/landing.html
Labels: hacktoberfest, hacktoberfest-accepted

#20 landing page
  index.css
  index.html
Labels: hacktoberfest

#21 Added Background svg
  css/about.css
  css/style.css
  pages/images/background.jpg
Labels: hacktoberfest-accepted

#23 Fixed the Navbar logo
  index.html
Labels: hacktoberfest-accepted

#28 Update gallery.css
  css/gallery.css
Labels: hacktoberfest-accepted
