Repository gdscjgec/Pictionary, pull requests merged in 2022-02, with the labels that each got.

#60 data correction
  contributors.html
  pages/gallery/birds.html
  pages/gallery/landing.html
Labels: JWOC, easy

#68 [Issue {63}] Adding Navbar to Gallery and Contribution page
  contributors.html
  css/navbar.css
  index.css
  index.html
  pages/about.html
  pages/gallery/landing.html
Labels: enhancement, JWOC, medium

#72 nav bar opening in new tab/nav bar opening in same tab
  index.html
Labels: JWOC, easy

#83 updated contributors card
  contributors.html
  css/contri_card.css
  pages/gallery/landing.html
Labels: enhancement, JWOC, medium

#106 contributers list updated
  js/contributors.js
Labels: JWOC, easy

#113 Contributors CRON integration with custom dataset initialization
  .github/workflows/main.yml
  .gitignore
  backend/index.js
  backend/utils/writeJson.js
  data.json
  dvX1eJ7Wb
  js/contributors.js
  package-lock.json
  package.json
Labels: enhancement, JWOC, hard

#114 Cron update (every 3 hours)
  .github/workflows/main.yml
  data.json
Labels: enhancement

#116 Tweaked the contributors cards
  css/contri_card.css
  data.json
  js/contributors.js
Labels: easy
